---
# tasks file for mysql_db

- name: Update apt
  apt:
    update_cache: yes
    cache_valid_time: 3600
  become: yes

- name: Install MySQL
  apt:
    name: "{{ item }}"
  with_items:  
    - mysql-server
    - python-mysqldb
  become: yes