---
# tasks file for mysql_db_user

- name: Add user for create DB
  mysql_user:
    name: "{{mysql_user}}"
    password: "{{mysql_password}}"
    priv: "*.*:ALL"
    state: present
  notify:
    - Start mysql
  become: yes

- name: Create DB
  mysql_db:
    name: "{{mysql_database}}"
    state: present
    login_user: "{{mysql_user}}"
    login_password: "{{mysql_password}}"
  become: yes